#!/usr/local/bin/php
<?php

use langdonglei\util\command\fastadmin\addon\Install;
use langdonglei\util\command\fastadmin\addon\Zip;
use Symfony\Component\Console\Application;

$root = dirname(__DIR__, 2);
if (!is_file($root . '/vendor/autoload.php')) {
    $root = dirname(__DIR__, 5);
}
define("ROOT_PATH", $root);
require ROOT_PATH . '/vendor/autoload.php';
if (is_file(ROOT_PATH . '/thinkphp/base.php')) {
    require ROOT_PATH . '/thinkphp/base.php';
}
const DS = DIRECTORY_SEPARATOR;

$application = new Application();
$application->add(new Install());
$application->add(new Zip());
$application->run();
