#!/usr/local/bin/php
<?php

use langdonglei\util\command\fastadmin\addon\Install;
use langdonglei\util\command\fastadmin\addon\Zip;
use Symfony\Component\Console\Application;

$root = dirname(__DIR__, 2);
if (!is_file($root . '/vendor/autoload.php')) {
    $root = dirname(__DIR__, 5);
}

define("ROOT_PATH", $root);
define("DS", DIRECTORY_SEPARATOR);

require ROOT_PATH . '/vendor/autoload.php';
require ROOT_PATH . '/thinkphp/base.php';

$application = new Application();
$application->add(new Install());
$application->add(new Zip());
$application->run();
