#!/usr/local/bin/php
<?php

use langdonglei\util\command\fastadmin\addon\Install;
use langdonglei\util\command\fastadmin\addon\Zip;
use Symfony\Component\Console\Application;

$root_path = dirname(__DIR__, 2);
if (!is_file($root_path . '/vendor/autoload.php')) {
    $root_path = dirname(__DIR__, 5);
}

define("ROOT_PATH", $root_path);

require ROOT_PATH . '/thinkphp/base.php';
require ROOT_PATH . '/vendor/autoload.php';

$application = new Application();
$application->add(new Install());
$application->add(new Zip());
$application->run();
